### ISSUE TITLE
Android: error: TypeError: Cannot read property 'ContextCompat' of undefined

### ISSUE THREAD

**Issue by delanick** [EddyVerbruggen/nativescript-pushy#13]
Getting the above error when trying to get push notification token, on Android. Used to work brilliantly. This could be an {N} 6 thing.

**Comment by EddyVerbruggen** [comment]
Yes indeed it is. Simple change, but I have other work to do first (Firebase plugin update, etc).

**Comment by delanick** [comment]
@EddyVerbruggen hahaha absolutely bud. I'm just getting these to you so you have them :)

This Pushy service is really nice to use, so I really hope this plugin becomes a Nativescript team priority at some point, really makes things easy! :)

**Comment by EddyVerbruggen** [comment]
Yep, and thanks for reporting it!

I think supporting it will fall to me in the foreseeable future. But I agree, it's a nice service although I don't use it anymore in a real app currently.

**Comment by delanick** [comment]
Yeah I find it super easy to use, which is the battle won!

Do you use the Firebase one? Would you rather recommend that?

**Comment by EddyVerbruggen** [comment]
I don't currently have an app with notifications at all. I only provide these to the community, and I like folks to have a choice. My personal preference is not too relevant.

**Comment by delanick** [comment]
Fair point :)

**Comment by EddyVerbruggen** [comment]
Fixed by #14, install version 2.0.0 for NativeScript 6 compatibility.

**Comment by delanick** [comment]
@EddyVerbruggen You're a hero, thanks so much!! Will install in the next hour or so. Will let you know if anything fails. :)

Do you have a roadmap of changes you'll be making in future versions of the plugin? :)

**Comment by EddyVerbruggen** [comment]
Cheers, and I'll pass the thanks to @markoImake because he did the legwork on this.

I don't have a roadmap for any of my plugins. It's almost always driven by feature requests posted as Github issues.

**Comment by delanick** [comment]
@EddyVerbruggen let me do that too. @markoImake thanks so much for your efforts, much appreciated! They'll help me continue my project.

@EddyVerbruggen ah ok that's what I wanna hear :) I've added a few requests (features and for documentation) to the issues list. If/when you do ever get time, please check it out. The most pressing one is to be able to determine whether the app was opened by clicking the notification or just the usually way by tapping the app icon. If opened by notification, I want the app to open and automatically navigate to the relevant page. I just don't know how to do that yet as I'm not seeing anything in the notification payload, or app startup logs that shows that the app was started by notification. So essentially, the notifications need to be managed via the various states the app can be in.

That's the most pressing for me personally. Notification buttons and stuff are a nice to have. Right now notifications only open the app on iOS and Android. But if the app is actively displayed on the screen, on iOS the notifications are received but not shown (may be an iOS thing, not sure) and on Android they automatically redirect the app to the relevant page whether the user clicks on them or not which is quite annoying (this I'm sure if my incorrect implementation of the notification handlers). This is why I need to know if the notification was tapped or now, and then handle that event :)

If and when you have time :) For now I'll survive I'm sure.

**Comment by EddyVerbruggen** [comment]
@delanick Let's move that discussion to #8. But if their SDK doesn't support it we need to find a workaround.

**Comment by delanick** [comment]
Hey @EddyVerbruggen I've installed the update via CLI (I usually use Sidekick) and now my device does get the token, but does not receive the notification - at all. iOS still works fine but Android doesn't even display it in the console, as if it never received it at all. Not sure what that may mean or how to fix it. The Pushy dashboard recognises the device correctly and has a matching token for it but still no notification is received. I've tried via the Pushy dashboard and their api from my server.

**Comment by delanick** [comment]
> Hey @EddyVerbruggen I've installed the update via CLI (I usually use Sidekick) and now my device does get the token, but does not receive the notification - at all. iOS still works fine but Android doesn't even display it in the console, as if it never received it at all. Not sure what that may mean or how to fix it. The Pushy dashboard recognises the device correctly and has a matching token for it but still no notification is received. I've tried via the Pushy dashboard and their api from my server.

That said though, I was also not asked for permission to receive notifications on the app's start up. Will unintall and reinstall and see.

**Comment by delanick** [comment]
@EddyVerbruggen Do you know which Android permissions I need to enable? Just want to confirm I have them correct.
