### ISSUE TITLE
Send the entire notification payload to the client

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-pushy#7]
Currently, when receiving a notification, we only send the `title` and `message` to the client. Let's copy the entire payload to a `data` object, so the app has some more flexibility.

**Comment by EddyVerbruggen** [comment]
It's all copied into a `data` object. Check the readme for details.

**Comment by delanick** [comment]
@EddyVerbruggen You legend! You did this sooner than expected. Can now pretty much complete my app! 

Cheers bud!
