### ISSUE TITLE
How to handle notification received and app opened by user tapping the notification

### ISSUE THREAD

**Issue by delanick** [EddyVerbruggen/nativescript-pushy#8]
Hey @EddyVerbruggen 

Not sure how to phrase this, so will just give it a go.

How do I handle the various use cases for receiving the notification? For example:

If the app is already in the foreground, or if opened by the user clicking on the notification (app closed or in background)...

I wrote a piece of code that navigates to an 'article' page based on the id and type in the 'data' payload of the notification, the catch is this:

- when app not in foreground, the error is that the notification can't be received as the navigate property cannot be read of undefined -> this makes sense as the app is not 'open' at that point. I didn't know the code would execute (or attempt to) when the app is not open in foreground, other than displaying the notification.

- When app is in foreground, the app automatically redirects/navigates to the 'article' page, which will annoy users endlessly when they're on a page and the app just navigates away.

How would we circumvent this? I'd like to be able to receive the notifications as normal, but only once the user taps on them does the handler execute (regardless of whether the app is in foreground or not). Any idea?

**Comment by EddyVerbruggen** [comment]
Is there anything in the [Pushy docs / SDK](https://pushy.me/docs) that we can leverage to check whether or not the app was launched by tapping the notification? Because I don't see it.

What we could do is add a `foreground: boolean` property to the notification payload that's passed to your app. It will be true if the notification was received while the app was in the foreground.

On iOS that's easy to implement, but I'm looking for the best way to do it on Android.

**Comment by delanick** [comment]
@EddyVerbruggen I've spoken with John from Pushy (one of the main devs there) and he mentioned that the SDK they create wasn't for Nativescript and that I'd need to  chat to you about it. They don't officially support Nativescript. I think a foreground Boolean would be fine in terms of stopping the app from automatically redirecting, but how do we ascertain whether the app was opened by clicking/tapping the notification? When tapping the notification, the handler needs to be executed nce the app opens, and there I have no clue how to implement that.

**Comment by delanick** [comment]
@EddyVerbruggen I've sent John an email to see if he has any ideas too. Will advise when I have his feedback :)

**Comment by EddyVerbruggen** [comment]
@delanick That's a weird statement by John. Of course their SDK wasn't created for NativeScript, but the problem is not NativeScript-specific, is it? Even native iOS and Android apps will have the same challenges as the one you described.

**Comment by EddyVerbruggen** [comment]
@delanick You could check their suggestion for their Cordova implementation to achieve this: https://github.com/pushy-me/pushy-cordova/issues/16 -- so add pause/resume listeners the NativeScript way and use that to determine whether or not you should navigate.

**Comment by delanick** [comment]
@EddyVerbruggen I may have paraphrased a bit, but yeah, it would have the same limitations on their Native SDKs. I was asking him in the context of NativeScript and he responded in the same context, until he told me to ask you as they don't provide support for NativeScript. I've asked him for clarity and advice in context of their SDK now - so hoping he'll be able to advise us on a way forward. 

I think go ahead with the foreground property so long as it will help either way when building the notification handler.

Only thing is, on iOS if the app is in foreground the notification isn't displayed, despite it and all its data being received, so we may need to display local notifications to the user with the data in it so that the user doesn't miss them. And then (if possible) handle the local notification tapped event to redirect the app... Really not sure.

**Comment by delanick** [comment]
> @delanick You could check their suggestion for their Cordova implementation to achieve this: [pushy-me/pushy-cordova#16](https://github.com/pushy-me/pushy-cordova/issues/16) -- so add pause/resume listeners the NativeScript way and use that to determine whether or not you should navigate.

@EddyVerbruggen  I did try that. Didn't work. The app goes through various states once you click on the notification, especially when killed and not active at all. I still have all my code written for it, just commented out. If you want I can send it to you. Maybe you can get it working.

**Comment by EddyVerbruggen** [comment]
To display a notification on iOS when in the foreground you have to do [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/6fe086271d8d421da43504f9587a0cf09e7faeb1/src/messaging/messaging.ios.ts#L541). If the SDK doesn't handle it we could probably add some logic to the plugin to make it work.

**Comment by delanick** [comment]
> To display a notification on iOS when in the foreground you have to do [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/6fe086271d8d421da43504f9587a0cf09e7faeb1/src/messaging/messaging.ios.ts#L541). If the SDK doesn't handle it we could probably add some logic to the plugin to make it work.

@EddyVerbruggen yeah I wouldn't even know where to add that. But will check it out.

**Comment by EddyVerbruggen** [comment]
I understand, it's more of a "note to self" ;)

**Comment by delanick** [comment]
@EddyVerbruggen LOL, cool :) I panicked a bit there.... had no clue what to do.

**Comment by delanick** [comment]
@EddyVerbruggen Let me know if I can help in any way, even if just to get info from John them.

**Comment by delanick** [comment]
@EddyVerbruggen I sent you John's response to your Gmail address.

Let me know if this all helps.

**Comment by delanick** [comment]
@EddyVerbruggen Did you change the permission request for the Android part? My app now asks for permission to access photos and media on the device, but on Android only, iOS still asks for permission to send notifications.

**Comment by EddyVerbruggen** [comment]
@delanick Yes, @delanick John's reply helped. I will release a new version today or tomorrow and you can rely on the new `appLaunchedByNotification` and `foreground` properties for routing logic.

Regarding the permissions, it was added based on recommendations in the Pushy SDK Android docs to not exhaust your account because this way your device saves the token locally and can reuse it when the app is reinstalled. On iOS they leverage the keychain to get the same behavior.

**Comment by EddyVerbruggen** [comment]
Also see the update docs @ https://github.com/EddyVerbruggen/nativescript-pushy#setnotificationhandler

**Comment by delanick** [comment]
> @delanick Yes, @delanick John's reply helped. I will release a new version today or tomorrow and you can rely on the new `appLaunchedByNotification` and `foreground` properties for routing logic.
> 
> Regarding the permissions, it was added based on recommendations in the Pushy SDK Android docs to not exhaust your account because this way your device saves the token locally and can reuse it when the app is reinstalled. On iOS they leverage the keychain to get the same behavior.

@EddyVerbruggen Apologies, only saw these now, was man-down this weekend (still am) with flu. Thanks so much for all if your help, you're an absolute legend bro!
